Repository Team-MoMo/MoMo_Android, pull requests merged in 2021-02, with the labels that each got.

#291 [fix] 암호잠금 설정 후 앱 실행시 close 버튼 누르면 홈 화면으로 진입하는 버그 해결 feature/#280
  app/src/main/java/com/momo/momo_android/lock/ui/LockOffActivity.kt
  app/src/main/java/com/momo/momo_android/lock/ui/LockOnActivity.kt
  app/src/main/java/com/momo/momo_android/lock/util/AppLifeCycleObserver.kt
  app/src/main/java/com/momo/momo_android/setting/ui/SettingActivity.kt
Labels: fix, yunso

#295 [refactor] 코드리뷰 반영 feature/#290
  app/src/main/java/com/momo/momo_android/home/adapter/ScrollGradientViewHolder.kt
  app/src/main/java/com/momo/momo_android/home/ui/HomeFragment.kt
  app/src/main/java/com/momo/momo_android/home/ui/ScrollFragment.kt
  app/src/main/java/com/momo/momo_android/util/Extension.kt
Labels: refactor, yunso

#300 [fix] activity_setting.xml 파일의 switch 색상 변경 feature/#298
  app/src/main/res/drawable/switch_setting_thumb_off.xml
  app/src/main/res/drawable/switch_setting_thumb_on.xml
  app/src/main/res/drawable/switch_setting_track_off.xml
  app/src/main/res/drawable/switch_setting_track_on.xml
  app/src/main/res/drawable/switch_setting_track_selector.xml
  app/src/main/res/values/colors.xml
Labels: fix, yunso

#306 [fix] 추천문장 조회 실패 에러처리, 뒤로가기 애니메이션 추가
  app/src/main/java/com/momo/momo_android/upload/ui/UploadDeepActivity.kt
  app/src/main/java/com/momo/momo_android/upload/ui/UploadSentenceActivity.kt
Labels: fix, hyunjin
